version: "1"

services:
  - type: web
    name: doxen-ai-voice
    region: oregon
    plan: starter
    env: docker

    buildCommand: "docker build -t doxen-ai-voice ."
    startCommand: "docker run -p $PORT:10000 doxen-ai-voice"

    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: ASSISTANT_PHONE_NUMBER
        sync: false
