version: "1"

services:
  - type: web
    name: doxen-ai-voice
    env: docker
    plan: starter
    region: oregon

    envVars:
      - key: OPENAI_API_KEY
      - key: TWILIO_ACCOUNT_SID
      - key: TWILIO_AUTH_TOKEN
      - key: ASSISTANT_PHONE_NUMBER
